default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  reconnect: false
  pool: 50
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  socket: <%= ENV['DATABASE_SOCKET'] %>
  variables:
    sql_mode: ""
development:
  <<: *default
  database: "rails_websocket"
test:
  <<: *default
  database: "rails_websocket"
